---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapache2
spec:
  selector:
    matchLabels:
      app: myapache2
  template:
    metadata:
      labels:
        app: myapache2
    spec:
      nodeName: ip-172-31-6-250
      containers:
      - name: myapache
        image: httpd
        ports:
        - containerPort: 81

---
apiVersion: v1
kind: Service
metadata:
  name: myapache2
spec:
  type: NodePort
  selector:
    app: myapache2
  ports:
  - port: 81
    targetPort: 81
    nodePort: 30081
