---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapache
spec:
  selector:
    matchLabels:
      app: myapache
  template:
    metadata:
      labels:
        app: myapache
    spec:
      nodeName: k8s
      containers:
      - name: myapache
        image: httpd
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapache
spec:
  type: NodePort
  selector:
    app: myapache
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
